### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by pronoyb07** [Adarshjain1338/Major_Project#1]
Fix the procedure of our web app, and write about section(Nidhi)

Enable Read More

Make a good Readme

JSON file se fetch karnege data

Table model implementation for displaying our fetched data

Fix Upload button

Fix share buttons

**Comment by Varun270** [comment]
@pronoyb07 No need to create a README.md file as this repository will be merged with the parent one. Better invest time on other essential tasks.

**Comment by pronoyb07** [comment]
colio
